export const images = [
  {
    id: 1,
    name: '4_1_c',
    temperature: 0,
    look: 'Casual',
    src: require('../assets/attire/4_1_c.jpg'),
  },
  {
    id: 2,
    name: '4_2_c',
    temperature: 0,
    look: 'Casual',
    src: require('../assets/attire/4_2_c.jpg'),
  },
  {
    id: 3,
    name: '4_3_m',
    temperature: 0,
    look: 'Modern',
    src: require('../assets/attire/4_3_m.jpg'),
  },
  {
    id: 4,
    name: '4_4_m',
    temperature: 4,
    look: 'Modern',
    src: require('../assets/attire/4_4_m.jpg'),
  },
  {
    id: 5,
    name: '4_5_s',
    temperature: 4,
    look: 'Street',
    src: require('../assets/attire/4_5_s.jpg'),
  },
  {
    id: 6,
    name: '4_6_c',
    temperature: 4,
    look: 'Casual',
    src: require('../assets/attire/4_6_c.jpg'),
  },
  {
    id: 7,
    name: '4_7_c',
    temperature: 4,
    look: 'Casual',
    src: require('../assets/attire/4_7_c.jpg'),
  },
  {
    id: 8,
    name: '4_8_c',
    temperature: 4,
    look: 'Casual',
    src: require('../assets/attire/4_8_c.jpg'),
  },
  {
    id: 9,
    name: '4_9_c',
    temperature: 4,
    look: 'Casual',
    src: require('../assets/attire/4_9_c.jpg'),
  },
  {
    id: 10,
    name: '4_10_c',
    temperature: 4,
    look: 'Casual',
    src: require('../assets/attire/4_10_c.jpg'),
  },
  {
    id: 11,
    name: '4_11_c',
    temperature: 4,
    look: 'Casual',
    src: require('../assets/attire/4_11_c.jpg'),
  },
  {
    id: 12,
    name: '4_12_m',
    temperature: 4,
    look: 'Modern',
    src: require('../assets/attire/4_12_m.jpg'),
  },
  {
    id: 13,
    name: '4_13_c',
    temperature: 4,
    look: 'Casual',
    src: require('../assets/attire/4_13_c.jpg'),
  },
  {
    id: 14,
    name: '4_14_c',
    temperature: 4,
    look: 'Casual',
    src: require('../assets/attire/4_14_c.jpg'),
  },
  {
    id: 15,
    name: '4_15_c',
    temperature: 4,
    look: 'Casual',
    src: require('../assets/attire/4_15_c.jpg'),
  },
  {
    id: 16,
    name: '4_16_c',
    temperature: 4,
    look: 'Casual',
    src: require('../assets/attire/4_16_c.jpg'),
  },
  {
    id: 17,
    name: '4_17_r',
    temperature: 4,
    look: 'Romantic',
    src: require('../assets/attire/4_17_r.jpg'),
  },
  {
    id: 18,
    name: '5_1_c',
    temperature: 5,
    look: 'Casual',
    src: require('../assets/attire/5_1_c.jpg'),
  },
  {
    id: 19,
    name: '5_2_m',
    temperature: 5,
    look: 'Modern',
    src: require('../assets/attire/5_2_m.jpg'),
  },
  {
    id: 20,
    name: '5_3_m',
    temperature: 5,
    look: 'Modern',
    src: require('../assets/attire/5_3_m.jpg'),
  },
  {
    id: 21,
    name: '5_4_c',
    temperature: 5,
    look: 'Casual',
    src: require('../assets/attire/5_4_c.jpg'),
  },
  {
    id: 22,
    name: '5_5_c',
    temperature: 5,
    look: 'Casual',
    src: require('../assets/attire/5_5_c.jpg'),
  },
  {
    id: 23,
    name: '5_6_m',
    temperature: 5,
    look: 'Modern',
    src: require('../assets/attire/5_6_m.jpg'),
  },
  {
    id: 24,
    name: '5_7_c',
    temperature: 5,
    look: 'Casual',
    src: require('../assets/attire/5_7_c.jpg'),
  },
  {
    id: 25,
    name: '5_8_c',
    temperature: 5,
    look: 'Casual',
    src: require('../assets/attire/5_8_c.jpg'),
  },
  {
    id: 26,
    name: '5_9_c',
    temperature: 5,
    look: 'Casual',
    src: require('../assets/attire/5_9_c.jpg'),
  },
  {
    id: 27,
    name: '5_10_m',
    temperature: 5,
    look: 'Modern',
    src: require('../assets/attire/5_10_m.jpg'),
  },
  {
    id: 28,
    name: '5_11_m',
    temperature: 5,
    look: 'Modern',
    src: require('../assets/attire/5_11_m.jpg'),
  },
  {
    id: 29,
    name: '5_12_c',
    temperature: 5,
    look: 'Casual',
    src: require('../assets/attire/5_12_c.jpg'),
  },
  {
    id: 30,
    name: '5_13_c',
    temperature: 5,
    look: 'Casual',
    src: require('../assets/attire/5_13_c.jpg'),
  },
  {
    id: 31,
    name: '5_14_a',
    temperature: 5,
    look: 'Amekaji',
    src: require('../assets/attire/5_14_a.jpg'),
  },
  {
    id: 32,
    name: '5_15_c',
    temperature: 5,
    look: 'Casual',
    src: require('../assets/attire/5_15_c.jpg'),
  },
  {
    id: 33,
    name: '5_16_m',
    temperature: 5,
    look: 'Modern',
    src: require('../assets/attire/5_16_m.jpg'),
  },
  {
    id: 34,
    name: '9_1_c',
    temperature: 9,
    look: 'Casual',
    src: require('../assets/attire/9_1_c.jpg'),
  },
  {
    id: 35,
    name: '9_2_c',
    temperature: 9,
    look: 'Casual',
    src: require('../assets/attire/9_2_c.jpg'),
  },
  {
    id: 36,
    name: '9_3_c',
    temperature: 9,
    look: 'Casual',
    src: require('../assets/attire/9_3_c.jpg'),
  },
  {
    id: 37,
    name: '9_4_m',
    temperature: 9,
    look: 'Modern',
    src: require('../assets/attire/9_4_m.jpg'),
  },
  {
    id: 38,
    name: '9_5_s',
    temperature: 9,
    look: 'Street',
    src: require('../assets/attire/9_5_s.jpg'),
  },
  {
    id: 39,
    name: '9_6_c',
    temperature: 9,
    look: 'Casual',
    src: require('../assets/attire/9_6_c.jpg'),
  },
  {
    id: 40,
    name: '9_7_m',
    temperature: 9,
    look: 'Modern',
    src: require('../assets/attire/9_7_m.jpg'),
  },
  {
    id: 41,
    name: '9_8_c',
    temperature: 9,
    look: 'Casual',
    src: require('../assets/attire/9_8_c.jpg'),
  },
  {
    id: 42,
    name: '9_9_s',
    temperature: 9,
    look: 'Street',
    src: require('../assets/attire/9_9_s.jpg'),
  },
  {
    id: 43,
    name: '9_10_c',
    temperature: 9,
    look: 'Casual',
    src: require('../assets/attire/9_10_c.jpg'),
  },
  {
    id: 44,
    name: '9_11_m',
    temperature: 9,
    look: 'Modern',
    src: require('../assets/attire/9_11_m.jpg'),
  },
  {
    id: 45,
    name: '9_12_c',
    temperature: 9,
    look: 'Casual',
    src: require('../assets/attire/9_12_c.jpg'),
  },
  {
    id: 46,
    name: '9_13_c',
    temperature: 9,
    look: 'Casual',
    src: require('../assets/attire/9_13_c.jpg'),
  },
  {
    id: 47,
    name: '9_14_a',
    temperature: 9,
    look: 'Amekaji',
    src: require('../assets/attire/9_14_a.jpg'),
  },
  {
    id: 48,
    name: '9_15_c',
    temperature: 9,
    look: 'Casual',
    src: require('../assets/attire/9_15_c.jpg'),
  },
  {
    id: 49,
    name: '9_16_a',
    temperature: 9,
    look: 'Amekaji',
    src: require('../assets/attire/9_16_a.jpg'),
  },
  {
    id: 50,
    name: '12_1_r',
    temperature: 12,
    look: 'Romantic',
    src: require('../assets/attire/12_1_r.jpg'),
  },
  {
    id: 51,
    name: '12_2_r',
    temperature: 12,
    look: 'Romantic',
    src: require('../assets/attire/12_2_r.jpg'),
  },
  {
    id: 52,
    name: '12_3_r',
    temperature: 12,
    look: 'Romantic',
    src: require('../assets/attire/12_3_r.jpg'),
  },
  {
    id: 53,
    name: '12_4_s',
    temperature: 12,
    look: 'Street',
    src: require('../assets/attire/12_4_s.jpg'),
  },
  {
    id: 54,
    name: '12_5_s',
    temperature: 12,
    look: 'Street',
    src: require('../assets/attire/12_5_s.jpg'),
  },
  {
    id: 55,
    name: '12_6_s',
    temperature: 12,
    look: 'Street',
    src: require('../assets/attire/12_6_s.jpg'),
  },
  {
    id: 56,
    name: '12_7_s',
    temperature: 12,
    look: 'Street',
    src: require('../assets/attire/12_7_s.jpg'),
  },
  {
    id: 57,
    name: '12_8_s',
    temperature: 12,
    look: 'Street',
    src: require('../assets/attire/12_8_s.jpg'),
  },
  {
    id: 58,
    name: '12_9_s',
    temperature: 12,
    look: 'Street',
    src: require('../assets/attire/12_9_s.jpg'),
  },
  {
    id: 59,
    name: '12_10_s',
    temperature: 12,
    look: 'Street',
    src: require('../assets/attire/12_10_s.jpg'),
  },
  {
    id: 60,
    name: '12_11_s',
    temperature: 12,
    look: 'Street',
    src: require('../assets/attire/12_11_s.jpg'),
  },
  {
    id: 61,
    name: '17_1_r',
    temperature: 17,
    look: 'Romantic',
    src: require('../assets/attire/17_1_r.jpg'),
  },
  {
    id: 62,
    name: '17_2_r',
    temperature: 17,
    look: 'Romantic',
    src: require('../assets/attire/17_2_r.jpg'),
  },
  {
    id: 63,
    name: '17_3_r',
    temperature: 17,
    look: 'Romantic',
    src: require('../assets/attire/17_3_r.jpg'),
  },
  {
    id: 64,
    name: '17_4_s',
    temperature: 17,
    look: 'Street',
    src: require('../assets/attire/17_4_s.jpg'),
  },
  {
    id: 65,
    name: '17_5_s',
    temperature: 17,
    look: 'Street',
    src: require('../assets/attire/17_5_s.jpg'),
  },
  {
    id: 66,
    name: '17_6_r',
    temperature: 17,
    look: 'Romantic',
    src: require('../assets/attire/17_6_r.jpg'),
  },
  {
    id: 67,
    name: '17_7_r',
    temperature: 17,
    look: 'Romantic',
    src: require('../assets/attire/17_7_r.jpg'),
  },
  {
    id: 68,
    name: '17_8_s',
    temperature: 17,
    look: 'Street',
    src: require('../assets/attire/17_8_s.jpg'),
  },
  {
    id: 69,
    name: '20_1_r',
    temperature: 20,
    look: 'Romantic',
    src: require('../assets/attire/20_1_r.jpg'),
  },
  {
    id: 70,
    name: '20_2_s',
    temperature: 20,
    look: 'Street',
    src: require('../assets/attire/20_2_s.jpg'),
  },
  {
    id: 71,
    name: '20_3_s',
    temperature: 20,
    look: 'Street',
    src: require('../assets/attire/20_3_s.jpg'),
  },
  {
    id: 72,
    name: '20_4_r',
    temperature: 20,
    look: 'Romantic',
    src: require('../assets/attire/20_4_r.jpg'),
  },
  {
    id: 73,
    name: '20_5_r',
    temperature: 20,
    look: 'Romantic',
    src: require('../assets/attire/20_5_r.jpg'),
  },
  {
    id: 74,
    name: '20_6_c',
    temperature: 20,
    look: 'Casual',
    src: require('../assets/attire/20_6_c.jpg'),
  },
  {
    id: 75,
    name: '20_7_m',
    temperature: 20,
    look: 'Modern',
    src: require('../assets/attire/20_7_m.jpg'),
  },
  {
    id: 76,
    name: '20_8_r',
    temperature: 20,
    look: 'Romantic',
    src: require('../assets/attire/20_8_r.jpg'),
  },
  {
    id: 77,
    name: '20_9_s',
    temperature: 20,
    look: 'Street',
    src: require('../assets/attire/20_9_s.jpg'),
  },
  {
    id: 78,
    name: '23_1_r',
    temperature: 23,
    look: 'Romantic',
    src: require('../assets/attire/23_1_r.jpg'),
  },
  {
    id: 79,
    name: '23_2_r',
    temperature: 23,
    look: 'Romantic',
    src: require('../assets/attire/23_2_r.jpg'),
  },
  {
    id: 80,
    name: '23_3_r',
    temperature: 23,
    look: 'Romantic',
    src: require('../assets/attire/23_3_r.jpg'),
  },
  {
    id: 81,
    name: '23_4_r',
    temperature: 23,
    look: 'Romantic',
    src: require('../assets/attire/23_4_r.jpg'),
  },
];

export const titleImages = [
  {
    id: 1,
    name: 'fw1.jpg',
    src: require('../assets/fw1.jpg'),
  },
  {
    id: 2,
    name: 'fw2.jpg',
    src: require('../assets/fw2.jpg'),
  },
  {
    id: 3,
    name: 'fw3.jpg',
    src: require('../assets/fw3.jpg'),
  },
  {
    id: 4,
    name: 'fw4.jpg',
    src: require('../assets/fw4.jpg'),
  },
  {
    id: 5,
    name: 'fw5.jpg',
    src: require('../assets/fw5.jpg'),
  },
];
